name = "candidatepage"
compatibility_date = "2024-12-23"
main = "./worker/index.ts"

[assets]
not_found_handling = "single-page-application"

[env.production]
name = "candidatepage-production"

[env.staging]  
name = "candidatepage-staging" 